name: pyls-memestra
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.7,<3.8.0a0
  - jupyterlab >=2,<3.0.0a0
  - notebook >=4.3.1
  - nodejs
  - black
  - flake8 >=3.5
  - isort
  - mypy
  - pip
  - pylint
  - python-language-server
  - ujson <=1.35
  - ruamel_yaml
  - pip:
      - jupyter-lsp
      - pyls-black
      - pyls-isort
      - pyls-mypy

