on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

name: Continuous Integration

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install runtime dependencies
        run: pip install -r requirements.txt

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest
